#유투브 댓글 추출

In [ ]:
!pip -q install google-api-python-client pandas openpyxl isodate tqdm

In [ ]:
import pandas as pd
import isodate
from tqdm import tqdm
from datetime import datetime, timezone
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# -----------------------------
# Helpers
# -----------------------------
def parse_duration_to_seconds(iso8601_duration: str) -> int:
    """ISO8601 duration (e.g., PT15M51S) -> seconds"""
    if not iso8601_duration:
        return 0
    try:
        return int(isodate.parse_duration(iso8601_duration).total_seconds())
    except Exception:
        return 0

def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i+n]

def parse_yt_datetime(dt_str: str):
    """YouTube ISO datetime (e.g., 2023-01-01T12:34:56Z) -> aware datetime (UTC)"""
    if not dt_str:
        return None
    try:
        return datetime.fromisoformat(dt_str.replace("Z", "+00:00"))
    except Exception:
        return None

def parse_date_yyyy_mm_dd(s: str):
    """YYYY-MM-DD -> date"""
    try:
        return datetime.strptime(s, "%Y-%m-%d").date()
    except Exception:
        return None

def get_video_category_map(service, region_code="KR", hl="ko-KR"):
    """
    videoCategories.list로 categoryId -> categoryTitle 매핑 생성
    """
    category_map = {}
    resp = service.videoCategories().list(
        part="snippet",
        regionCode=region_code,
        hl=hl
    ).execute()

    for item in resp.get("items", []):
        cid = item.get("id", "")
        title = item.get("snippet", {}).get("title", "")
        category_map[cid] = title

    return category_map

# -----------------------------
# 1) API Key 입력 -> service 생성
# -----------------------------
api_key = input("1) YouTube API Key를 입력하세요: ").strip()
youtube = build("youtube", "v3", developerKey=api_key)

# 카테고리 매핑 미리 로드
VIDEO_CATEGORY_MAP = get_video_category_map(youtube, region_code="KR", hl="ko-KR")

# -----------------------------
# 2) 채널명 입력 -> 채널 후보 검색 -> 선택
# -----------------------------
channel_query = input("\n2) 추출하고자 하는 '채널명'을 입력하세요: ").strip()

def search_channels_by_name(service, query, max_results=5):
    resp = service.search().list(
        part="snippet",
        q=query,
        type="channel",
        maxResults=max_results
    ).execute()
    items = resp.get("items", [])
    results = []
    for it in items:
        ch_id = it["snippet"]["channelId"]
        title = it["snippet"]["title"]
        desc = it["snippet"].get("description", "")
        published_at = it["snippet"].get("publishedAt", "")
        results.append({
            "channelId": ch_id,
            "channelTitle": title,
            "description": desc,
            "publishedAt": published_at
        })
    return results

cands = search_channels_by_name(youtube, channel_query, max_results=5)
if not cands:
    raise ValueError("채널 검색 결과가 없습니다. 채널명을 다르게 입력해보세요.")

print("\n[채널 후보 목록]")
for i, c in enumerate(cands):
    print(f"{i}: {c['channelTitle']}  (channelId={c['channelId']})  created={c['publishedAt']}")

sel = input("원하는 채널 번호를 입력하세요 (기본 0): ").strip()
sel_idx = int(sel) if sel else 0
sel_idx = max(0, min(sel_idx, len(cands)-1))

channel_id = cands[sel_idx]["channelId"]
channel_title = cands[sel_idx]["channelTitle"]
print(f"\n선택된 채널: {channel_title} (channelId={channel_id})")

# -----------------------------
# 2.5) 기간 옵션 입력 (Enter면 전체)
# -----------------------------
print("\n[기간 필터 옵션]")
print("- 게시일(publishedAt) 기준으로 필터합니다.")
print("- 기간을 설정하지 않으려면 그냥 Enter를 누르세요.")
start_in = input("시작일 (YYYY-MM-DD) [Enter=미설정]: ").strip()
end_in   = input("종료일 (YYYY-MM-DD) [Enter=미설정]: ").strip()

start_date = parse_date_yyyy_mm_dd(start_in) if start_in else None
end_date   = parse_date_yyyy_mm_dd(end_in) if end_in else None

if start_in and not start_date:
    raise ValueError("시작일 형식이 올바르지 않습니다. YYYY-MM-DD 형식으로 입력하세요.")
if end_in and not end_date:
    raise ValueError("종료일 형식이 올바르지 않습니다. YYYY-MM-DD 형식으로 입력하세요.")

if start_date and end_date and start_date > end_date:
    raise ValueError("시작일이 종료일보다 늦습니다. 날짜를 다시 입력하세요.")

if start_date or end_date:
    print(f"기간 필터 활성화: start={start_date} / end={end_date}")
else:
    print("기간 필터 미사용: 전체 영상 대상")

# -----------------------------
# 3) 채널 uploads playlistId 얻기
# -----------------------------
def get_uploads_playlist_id(service, channel_id):
    resp = service.channels().list(
        part="contentDetails,snippet",
        id=channel_id,
        maxResults=1
    ).execute()
    items = resp.get("items", [])
    if not items:
        raise ValueError("channels.list에서 채널 정보를 못 가져왔습니다. channelId를 확인하세요.")
    uploads = items[0]["contentDetails"]["relatedPlaylists"]["uploads"]
    ch_title = items[0]["snippet"]["title"]
    return uploads, ch_title

uploads_playlist_id, channel_title_exact = get_uploads_playlist_id(youtube, channel_id)

# -----------------------------
# 4) 업로드 영상 목록(제목/ID/게시일) 가져오기
# -----------------------------
def list_all_uploaded_videos(service, uploads_playlist_id):
    videos_basic = []
    page_token = None
    while True:
        resp = service.playlistItems().list(
            part="snippet,contentDetails",
            playlistId=uploads_playlist_id,
            maxResults=50,
            pageToken=page_token
        ).execute()

        for it in resp.get("items", []):
            vid = it["contentDetails"]["videoId"]
            title = it["snippet"].get("title", "")
            published_at = it["contentDetails"].get("videoPublishedAt", it["snippet"].get("publishedAt", ""))
            videos_basic.append({
                "videoId": vid,
                "title": title,
                "publishedAt": published_at
            })

        page_token = resp.get("nextPageToken")
        if not page_token:
            break
    return videos_basic

videos_basic_all = list_all_uploaded_videos(youtube, uploads_playlist_id)
print(f"\n업로드 영상 수(전체 기본 목록): {len(videos_basic_all):,}")

# -----------------------------
# 5) 기간 필터 적용 (basic 목록 단계에서 1차 필터)
# -----------------------------
def filter_by_date_basic(videos_basic, start_date=None, end_date=None):
    if not (start_date or end_date):
        return videos_basic

    filtered = []
    for v in videos_basic:
        dt = parse_yt_datetime(v.get("publishedAt", ""))
        if not dt:
            filtered.append(v)
            continue
        d = dt.date()
        if start_date and d < start_date:
            continue
        if end_date and d > end_date:
            continue
        filtered.append(v)
    return filtered

videos_basic = filter_by_date_basic(videos_basic_all, start_date, end_date)
print(f"기간 필터 후 영상 수(1차): {len(videos_basic):,}")

if len(videos_basic) == 0:
    raise ValueError("기간 필터 결과 영상이 0개입니다. 날짜 범위를 다시 확인하세요.")

# -----------------------------
# 6) videos.list로 duration 등 상세정보 붙이기
#    + categoryId, categoryTitle, topicCategories 추가
# -----------------------------
def enrich_videos_with_details(service, videos_basic, category_map):
    basic_map = {v["videoId"]: v for v in videos_basic}
    video_ids = list(basic_map.keys())

    enriched = []
    for batch in tqdm(list(chunks(video_ids, 50)), desc="영상 상세정보 수집(videos.list)"):
        resp = service.videos().list(
            part="contentDetails,snippet,statistics,status,topicDetails",
            id=",".join(batch),
            maxResults=50
        ).execute()

        for it in resp.get("items", []):
            vid = it["id"]
            title = it["snippet"].get("title", basic_map.get(vid, {}).get("title", ""))
            published_at = it["snippet"].get("publishedAt", basic_map.get(vid, {}).get("publishedAt", ""))

            duration_iso = it["contentDetails"].get("duration", "")
            duration_sec = parse_duration_to_seconds(duration_iso)

            # Shorts 휴리스틱: 60초 이하
            is_shorts = duration_sec <= 60 and duration_sec > 0

            category_id = it["snippet"].get("categoryId", "")
            category_title = category_map.get(category_id, "")
            topic_categories = it.get("topicDetails", {}).get("topicCategories", [])

            enriched.append({
                "channelTitle": it["snippet"].get("channelTitle", channel_title_exact),
                "videoId": vid,
                "title": title,
                "publishedAt": published_at,
                "duration_iso": duration_iso,
                "duration_seconds": duration_sec,
                "format": "Shorts" if is_shorts else "Longform",
                "categoryId": category_id,
                "categoryTitle": category_title,
                "topicCategories": " | ".join(topic_categories),
                "viewCount": it.get("statistics", {}).get("viewCount", None),
                "likeCount": it.get("statistics", {}).get("likeCount", None),
                "commentCount": it.get("statistics", {}).get("commentCount", None),
                "privacyStatus": it.get("status", {}).get("privacyStatus", None)
            })

    df = pd.DataFrame(enriched)
    df.sort_values(by="publishedAt", ascending=False, inplace=True, ignore_index=True)
    return df

df_videos = enrich_videos_with_details(youtube, videos_basic, VIDEO_CATEGORY_MAP)

# -----------------------------
# 7) 기간 필터 2차 안전망
# -----------------------------
def filter_df_by_date(df, start_date=None, end_date=None):
    if not (start_date or end_date) or df.empty:
        return df
    keep = []
    for _, row in df.iterrows():
        dt = parse_yt_datetime(row.get("publishedAt", ""))
        if not dt:
            keep.append(True)
            continue
        d = dt.date()
        if start_date and d < start_date:
            keep.append(False)
            continue
        if end_date and d > end_date:
            keep.append(False)
            continue
        keep.append(True)
    return df.loc[keep].reset_index(drop=True)

df_videos = filter_df_by_date(df_videos, start_date, end_date)

# -----------------------------
# 8) 쇼츠만 남기기
# -----------------------------
df_videos = df_videos[df_videos["format"] == "Shorts"].reset_index(drop=True)

print(f"\n기간+쇼츠 필터 후 영상 수(최종): {len(df_videos):,}")

if len(df_videos) == 0:
    raise ValueError("조건에 맞는 쇼츠 영상이 0개입니다. 날짜 범위를 다시 확인하세요.")

print(df_videos.head(3))

# -----------------------------
# 9) 댓글 추출 (쇼츠 영상에 대해서만)
# -----------------------------
INCLUDE_REPLIES = True  # 답글까지 포함하려면 True, 아니면 False

def fetch_replies_for_comment(service, parent_comment_id):
    replies = []
    page_token = None
    while True:
        resp = service.comments().list(
            part="snippet",
            parentId=parent_comment_id,
            maxResults=100,
            pageToken=page_token,
            textFormat="plainText"
        ).execute()

        for it in resp.get("items", []):
            sn = it["snippet"]
            replies.append({
                "comment_type": "reply",
                "comment_id": it["id"],
                "parent_comment_id": parent_comment_id,
                "author": sn.get("authorDisplayName", ""),
                "text": sn.get("textDisplay", ""),
                "like_count": sn.get("likeCount", 0),
                "published_at": sn.get("publishedAt", ""),
                "updated_at": sn.get("updatedAt", "")
            })

        page_token = resp.get("nextPageToken")
        if not page_token:
            break
    return replies

def fetch_comments_for_video(service, video_id):
    rows = []
    page_token = None
    try:
        while True:
            resp = service.commentThreads().list(
                part="snippet",
                videoId=video_id,
                maxResults=100,
                pageToken=page_token,
                textFormat="plainText"
            ).execute()

            for it in resp.get("items", []):
                sn = it["snippet"]["topLevelComment"]["snippet"]
                top_comment_id = it["snippet"]["topLevelComment"]["id"]
                total_reply = it["snippet"].get("totalReplyCount", 0)

                rows.append({
                    "comment_type": "top",
                    "comment_id": top_comment_id,
                    "parent_comment_id": "",
                    "author": sn.get("authorDisplayName", ""),
                    "text": sn.get("textDisplay", ""),
                    "like_count": sn.get("likeCount", 0),
                    "published_at": sn.get("publishedAt", ""),
                    "updated_at": sn.get("updatedAt", ""),
                    "total_reply_count": total_reply
                })

                if INCLUDE_REPLIES and total_reply and total_reply > 0:
                    try:
                        replies = fetch_replies_for_comment(service, top_comment_id)
                        for r in replies:
                            r["total_reply_count"] = ""
                            rows.append(r)
                    except HttpError:
                        pass

            page_token = resp.get("nextPageToken")
            if not page_token:
                break

    except HttpError as e:
        return [{"_error": str(e)}]

    return rows

comment_rows = []
for _, v in tqdm(df_videos.iterrows(), total=len(df_videos), desc="댓글 수집(commentThreads.list)"):
    vid = v["videoId"]
    title = v["title"]

    rows = fetch_comments_for_video(youtube, vid)

    if rows and isinstance(rows, list) and rows[0].get("_error"):
        comment_rows.append({
            "video_title": title,
            "video_id": vid,
            "comment_type": "ERROR",
            "comment_id": "",
            "parent_comment_id": "",
            "author": "",
            "text": rows[0]["_error"],
            "like_count": "",
            "published_at": "",
            "updated_at": "",
            "total_reply_count": ""
        })
        continue

    if not rows:
        comment_rows.append({
            "video_title": title,
            "video_id": vid,
            "comment_type": "NO_COMMENTS",
            "comment_id": "",
            "parent_comment_id": "",
            "author": "",
            "text": "",
            "like_count": "",
            "published_at": "",
            "updated_at": "",
            "total_reply_count": ""
        })
        continue

    for i, r in enumerate(rows):
        comment_rows.append({
            "video_title": title if i == 0 else "",
            "video_id": vid if i == 0 else "",
            "comment_type": r.get("comment_type", ""),
            "comment_id": r.get("comment_id", ""),
            "parent_comment_id": r.get("parent_comment_id", ""),
            "author": r.get("author", ""),
            "text": r.get("text", ""),
            "like_count": r.get("like_count", ""),
            "published_at": r.get("published_at", ""),
            "updated_at": r.get("updated_at", ""),
            "total_reply_count": r.get("total_reply_count", "")
        })

df_comments = pd.DataFrame(comment_rows)
print("\n댓글 행 수:", len(df_comments))

# -----------------------------
# 10) 엑셀 저장
# -----------------------------
suffix = ""
if start_date or end_date:
    suffix = f"_{start_date if start_date else 'NA'}_{end_date if end_date else 'NA'}"

out_path = f"{channel_title_exact}_youtube_export_shorts_only_with_category{suffix}.xlsx".replace("/", "_").replace("\\", "_")

with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
    df_videos.to_excel(writer, sheet_name="videos", index=False)
    df_comments.to_excel(writer, sheet_name="comments", index=False)

    ws_v = writer.sheets["videos"]
    ws_c = writer.sheets["comments"]
    ws_v.freeze_panes = "A2"
    ws_c.freeze_panes = "A2"

print("\n저장 완료:", out_path)

try:
    from google.colab import files
    files.download(out_path)
except Exception:
    print("다운로드는 코랩 환경에서만 자동으로 됩니다. 파일 경로:", out_path)

1) YouTube API Key를 입력하세요: AIzaSyA-EXCIpzuNe_ezfd3NPb8wVZ64Mw7xpnY

2) 추출하고자 하는 '채널명'을 입력하세요: 유다빈밴드 YdBB

[채널 후보 목록]
0: 유다빈밴드 YdBB  (channelId=UCxJsy4OiC7sKeuwYtL_1FhA)  created=2022-11-01T05:41:18Z
1: YdBB - Topic  (channelId=UCw-JbV7l4MwJjfd14QvKteQ)  created=2021-03-31T02:31:02Z
2: Sally Park  (channelId=UCP_bolRS78MzD6oKiyavYZA)  created=2025-11-15T14:52:56Z
3: 유다빈밴드 진심녀  (channelId=UCoZkM8HPG3-v450t_YssTYQ)  created=2023-03-28T05:54:11Z
4: 빠계진밴드 BBB  (channelId=UCVVC9HQxl5k75AtVyW1H2pg)  created=2025-05-19T08:50:58Z
원하는 채널 번호를 입력하세요 (기본 0): 0

선택된 채널: 유다빈밴드 YdBB (channelId=UCxJsy4OiC7sKeuwYtL_1FhA)

[기간 필터 옵션]
- 게시일(publishedAt) 기준으로 필터합니다.
- 기간을 설정하지 않으려면 그냥 Enter를 누르세요.
시작일 (YYYY-MM-DD) [Enter=미설정]: 2025-09-11
종료일 (YYYY-MM-DD) [Enter=미설정]: 2025-09-16
기간 필터 활성화: start=2025-09-11 / end=2025-09-16

업로드 영상 수(전체 기본 목록): 260
기간 필터 후 영상 수(1차): 5

영상 상세정보 수집(videos.list): 100%|██████████| 1/1 [00:00<00:00, 14.52it/s]

기간+쇼츠 필터 후 영상 수(최종): 2
  channelTitle      videoId  \
0   유다빈밴드 YdBB  _HZ5JUjF9AU
1   유다빈밴드 YdBB  zE9hkEdKLMc

                                               title           publishedAt  \
0                           유다빈밴드 - 어지러워 | MV Teaser  2025-09-14T10:00:02Z
1  유다빈밴드 - 20s Music Video OUT NOW! release on 25...  2025-09-12T10:00:19Z

  duration_iso  duration_seconds  format categoryId categoryTitle  \
0        PT43S                43  Shorts         22        인물/블로그
1        PT39S                39  Shorts         22        인물/블로그

                                     topicCategories viewCount likeCount  \
0                https://en.wikipedia.org/wiki/Music      3347       174
1  https://en.wikipedia.org/wiki/Music | https://...   1196080      2976

  commentCount privacyStatus
0           10        public
1            9        public

댓글 수집(commentThreads.list): 100%|██████████| 2/2 [00:00<00:00,  5.77it/s]

댓글 행 수: 19

저장 완료: 유다빈밴드 YdBB_youtube_export_shorts_only_with_category_2025-09-11_2025-09-16.xlsx

#이모지, 특수문자 제거

In [ ]:
!pip -q install emoji openpyxl pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 9.7 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import re
import emoji
from google.colab import files

# 1) 파일 업로드
uploaded = files.upload()
in_path = next(iter(uploaded.keys()))
print("업로드된 파일:", in_path)

# 2) 제거할 기호들: ! ~ ^ ? . , (전각 포함)
punct_pattern = re.compile(r"[!！~～\^?？,，\.．]+")

def clean_text(x):
    if pd.isna(x):
        return x
    s = str(x)

    # 이모지 제거 (✅ 한글 보존)
    s = emoji.replace_emoji(s, replace="")

    return s

# 3) 엑셀 로드 및 검증
xls = pd.ExcelFile(in_path)
if "comments" not in xls.sheet_names:
    raise ValueError(f"'comments' 시트를 찾지 못했습니다. 현재 시트: {xls.sheet_names}")

df_comments = pd.read_excel(in_path, sheet_name="comments")
if "text" not in df_comments.columns:
    raise ValueError(f"'text' 컬럼이 없습니다. 현재 컬럼: {list(df_comments.columns)}")

# 4) text 컬럼만 전처리
df_comments["text"] = df_comments["text"].apply(clean_text)

# 5) 다른 시트는 그대로 유지하면서 저장
out_path = in_path.replace(".xlsx", "") + "_clean.xlsx"
with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
    for sh in xls.sheet_names:
        df = pd.read_excel(in_path, sheet_name=sh)
        if sh == "comments":
            df["text"] = df_comments["text"]
        df.to_excel(writer, sheet_name=sh, index=False)

print("저장 완료:", out_path)
files.download(out_path)

Saving 르세라핌.xlsx to 르세라핌.xlsx
업로드된 파일: 르세라핌.xlsx
저장 완료: 르세라핌_clean.xlsx

#언어 분리 (알파벳/한국어/일본어/중국어/기타)

In [ ]:
!pip -q install pandas openpyxl

In [ ]:
import pandas as pd
import re
from google.colab import files

# 1) 파일 업로드
uploaded = files.upload()
in_path = next(iter(uploaded.keys()))
print("업로드된 파일:", in_path)

# 2) 엑셀 로드
xls = pd.ExcelFile(in_path)
if "comments" not in xls.sheet_names:
    raise ValueError(f"'comments' 시트를 찾지 못했습니다. 현재 시트: {xls.sheet_names}")

df_comments = pd.read_excel(in_path, sheet_name="comments")

required_cols = ["video_title", "video_id", "comment_type", "text"]
missing_cols = [c for c in required_cols if c not in df_comments.columns]
if missing_cols:
    raise ValueError(f"필수 컬럼이 없습니다: {missing_cols}\n현재 컬럼: {list(df_comments.columns)}")

# 3) video_title / video_id 아래 행까지 채우기
def blank_to_na(series):
    return series.replace(r"^\s*$", pd.NA, regex=True)

df_comments["video_title_filled"] = blank_to_na(df_comments["video_title"]).ffill()
df_comments["video_id_filled"] = blank_to_na(df_comments["video_id"]).ffill()

# 4) 문자(스크립트) 패턴
re_hangul = re.compile(r"[가-힣ㄱ-ㅎㅏ-ㅣ\u3130-\u318F]")
re_kana   = re.compile(r"[\u3040-\u309F\u30A0-\u30FF\u31F0-\u31FF]")
re_alpha  = re.compile(r"[A-Za-z]")
re_hanzi  = re.compile(r"[\u4E00-\u9FFF]")

def classify_script_priority(text):
    """
    우선순위:
    1) 한글
    2) 일본어(가나)
    3) 알파벳
    4) 한자
    5) 기타
    """
    if pd.isna(text):
        return "OTHER"
    s = str(text)
    if not s.strip():
        return "OTHER"

    if re_hangul.search(s):
        return "HANGUL"
    if re_kana.search(s):
        return "JAPANESE"
    if re_alpha.search(s):
        return "ALPHABET"
    if re_hanzi.search(s):
        return "CHINESE"
    return "OTHER"

# 5) 실제 댓글만 남기기
# ERROR / NO_COMMENTS 행 제외
df_valid = df_comments[
    df_comments["comment_type"].astype(str).isin(["top", "reply"])
].copy()

df_valid = df_valid[df_valid["text"].notna()]
df_valid = df_valid[df_valid["text"].astype(str).str.strip() != ""]

# 6) 언어 분류
df_valid["lang_group"] = df_valid["text"].apply(classify_script_priority)

# 7) 영상별 언어 개수 집계
lang_order = ["HANGUL", "JAPANESE", "ALPHABET", "CHINESE", "OTHER"]

df_summary = (
    df_valid
    .groupby(["video_title_filled", "video_id_filled", "lang_group"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

# 없는 언어 컬럼도 0으로 추가
for col in lang_order:
    if col not in df_summary.columns:
        df_summary[col] = 0

# 컬럼 순서 정리
df_summary = df_summary[
    ["video_title_filled", "video_id_filled"] + lang_order
].copy()

# 총 댓글 수
df_summary["TOTAL"] = df_summary[lang_order].sum(axis=1)

# 비율 컬럼도 추가하고 싶으면 아래 사용
for col in lang_order:
    df_summary[f"{col}_PCT"] = (df_summary[col] / df_summary["TOTAL"] * 100).round(2)

# 컬럼명 보기 좋게 변경
df_summary = df_summary.rename(columns={
    "video_title_filled": "video_title",
    "video_id_filled": "video_id"
})

# 8) 저장
out_path = in_path.replace(".xlsx", "") + "_video_language_summary.xlsx"

with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
    # 원본 시트 유지
    for sh in xls.sheet_names:
        df_sh = pd.read_excel(in_path, sheet_name=sh)
        df_sh.to_excel(writer, sheet_name=sh[:31], index=False)

    # 영상별 언어 요약 시트
    df_summary.to_excel(writer, sheet_name="VIDEO_LANG_SUMMARY", index=False)

    # 분류된 실제 댓글 시트도 같이 저장하고 싶으면
    df_valid.to_excel(writer, sheet_name="COMMENTS_CLASSIFIED", index=False)

    writer.sheets["VIDEO_LANG_SUMMARY"].freeze_panes = "A2"
    writer.sheets["COMMENTS_CLASSIFIED"].freeze_panes = "A2"

print("저장 완료:", out_path)
print(df_summary.head())

files.download(out_path)

Saving 르세라핌_clean.xlsx to 르세라핌_clean (2).xlsx
업로드된 파일: 르세라핌_clean (2).xlsx
저장 완료: 르세라핌_clean (2)_video_language_summary.xlsx
lang_group                                        video_title     video_id  \
0           #ATEEZ #SAN is built DIFFERENT🍋 #LE_SSERAFIM #...  XpX0xmaYyks
1           #BANGJEEMIN #CHOIJUNGEUN, come over and dance!...  5uqYc-IrSrY
2           #BANGJEEMIN is burning 𝓗𝓞𝓣🧲🐱#LE_SSERAFIM #르세라핌...  CNSFLyhb6n0
3           #BabyDONTCry #Yihyun #Beni are built DIFFERENT...  SN7OG1x5ero
4           #Boona is built DIFFERENT🐷 #LE_SSERAFIM #르세라핌 ...  qqtnGJ_8094

lang_group  HANGUL  JAPANESE  ALPHABET  CHINESE  OTHER  TOTAL  HANGUL_PCT  \
0               22        24       105        1      4    156       14.10
1               55        19       120        0      3    197       27.92
2               71        26       128        1      7    233       30.47
3               35        22        70        0      5    132       26.52
4               22        23        35        0      3     83       26.51

lang_group  JAPANESE_PCT  ALPHABET_PCT  CHINESE_PCT  OTHER_PCT
0                  15.38         67.31         0.64       2.56
1                   9.64         60.91         0.00       1.52
2                  11.16         54.94         0.43       3.00
3                  16.67         53.03         0.00       3.79
4                  27.71         42.17         0.00       3.61

In [ ]:
# =========================================
# 1. 라이브러리 불러오기
# =========================================
import pandas as pd
import numpy as np
from google.colab import files
from scipy.stats import spearmanr

# =========================================
# 2. 엑셀 파일 업로드
# =========================================
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print(f"업로드된 파일: {file_name}")

# =========================================
# 3. 첫 번째 시트 불러오기
# =========================================
df = pd.read_excel(file_name, sheet_name=0)

print("\n[데이터 미리보기]")
display(df.head())

print("\n[전체 칼럼명 목록]")
print(df.columns.tolist())

# =========================================
# 4. 사용할 칼럼명 지정
# 엑셀 파일의 칼럼명과 정확히 같아야 함
# =========================================
columns_for_corr = [
    '조회수',
    '좋아요수',
    '댓글수',
    '좋아요율',
    '댓글율',
    '알파벳비율',
    '한글비율',
    '일어비율'
]

# =========================================
# 5. 필요한 칼럼만 추출
# =========================================
data = df[columns_for_corr].copy()

# =========================================
# 6. 숫자형 변환
# =========================================
for col in columns_for_corr:
    data[col] = (
        data[col]
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.replace('%', '', regex=False)
        .str.strip()
    )
    data[col] = pd.to_numeric(data[col], errors='coerce')

print("\n[숫자형 변환 후 데이터 미리보기]")
display(data.head())

# =========================================
# 7. 결측치 제거
# =========================================
data_clean = data.dropna()

print(f"\n원본 행 개수: {len(data)}")
print(f"결측치 제거 후 행 개수: {len(data_clean)}")

# =========================================
# 8. 스피어만 상관분석
# =========================================
corr_matrix = data_clean.corr(method='spearman')

print("\n[스피어만 상관계수 행렬]")
display(corr_matrix)

# =========================================
# 9. p-value 계산 (수정 버전)
# =========================================
corr_coef = pd.DataFrame(index=columns_for_corr, columns=columns_for_corr, dtype=float)
p_value = pd.DataFrame(index=columns_for_corr, columns=columns_for_corr, dtype=float)

for col1 in columns_for_corr:
    for col2 in columns_for_corr:
        if col1 == col2:
            corr_coef.loc[col1, col2] = 1.0
            p_value.loc[col1, col2] = 0.0
        else:
            valid = data_clean[[col1, col2]].dropna()

            # 두 변수 모두 상수값이면 spearmanr가 nan 반환 가능
            if valid[col1].nunique() < 2 or valid[col2].nunique() < 2:
                corr_coef.loc[col1, col2] = np.nan
                p_value.loc[col1, col2] = np.nan
            else:
                coef, p = spearmanr(valid[col1], valid[col2])
                corr_coef.loc[col1, col2] = float(coef)
                p_value.loc[col1, col2] = float(p)

print("\n[상관계수]")
display(corr_coef)

print("\n[p-value]")
display(p_value)

# =========================================
# 10. CSV 저장
# =========================================
corr_matrix.to_csv('correlation_matrix_spearman.csv', encoding='utf-8-sig')
corr_coef.to_csv('correlation_coef.csv', encoding='utf-8-sig')
p_value.to_csv('correlation_p_value.csv', encoding='utf-8-sig')

print("\n저장 완료:")
print("- correlation_matrix_spearman.csv")
print("- correlation_coef.csv")
print("- correlation_p_value.csv")

# =========================================
# 11. 내 컴퓨터로 다운로드
# =========================================
from google.colab import files

files.download('correlation_matrix_spearman.csv')
files.download('correlation_coef.csv')
files.download('correlation_p_value.csv')

Saving 르세라핌_실험.xlsx to 르세라핌_실험.xlsx
업로드된 파일: 르세라핌_실험.xlsx

[데이터 미리보기]

,videoId,title,publishedAt,duration_iso,duration_seconds,장르,조회수,좋아요수,댓글수,좋아요율,...,장르별 평균 조회수,장르별 평균 좋아요수,장르별 평균 댓글수,장르별 평균 좋아요율,장르별 평균 댓글율,장르별 평균 알파벳비율,장르별 평균 한글비율,장르별 평균 일어비율,장르별 평균 중국어비율,장르별 평균 기타비율
0,pNq0Obxkq-s,𝕆𝕙 𝕀 𝕜𝕟𝕠𝕨 𝕪𝕠𝕦 𝕨𝕒𝕟𝕥 𝕥𝕠 𝕥𝕒𝕜𝕖 𝕞𝕪 𝕙𝕒𝕟𝕕 🫴 #LE_SSERA...,2025-03-31T03:59:53Z,PT21S,21,Music,2954525,93382,388,0.031606,...,1367262.909524,55934.27619,345.066667,0.060447,0.000548,58.757857,23.415714,14.874857,0.707905,2.243286
1,85Mh3ktbTVk,ⓒⓞⓜⓔ ⓞⓥⓔⓡ #LE_SSERAFIM #르세라핌 #KIMCHAEWON#김채원 #...,2025-03-31T08:59:19Z,PT17S,17,Music,3492325,80323,407,0.023000,...,1912843.625,56566.10119,395.035714,0.053832,0.000486,55.289405,29.687083,12.04744,0.792381,2.18369
2,4V3D7IolGEc,ⓐⓝⓓ ⓓⓐⓝⓒⓔ #LE_SSERAFIM #르세라핌 #HUHYUNJIN#허윤진 #H...,2025-03-31T09:15:17Z,PT17S,17,Entertainment,2638697,64422,247,0.024414,...,516533.926606,25638.963303,240.431193,0.064161,0.000704,55.684771,28.768532,12.972477,0.692936,1.881284
3,iL57ykhVGUk,🙂‍↔️🙂‍↔️🙂‍↔️ #LE_SSERAFIM #르세라핌 #LE_SSERAFIM_H...,2025-03-31T09:30:20Z,PT13S,13,Entertainment,2645603,63850,358,0.024134,...,1322577.066667,54462.613333,389.986667,0.056531,0.000484,58.403867,21.3644,17.142533,0.926267,2.1624
4,r30ioZpuQ0M,"#android, come over and dance!🕺💚 #LE_SSERAFIM ...",2025-04-01T09:30:18Z,PT14S,14,Entertainment,283185,19425,129,0.068595,...,1120583.827586,50105.448276,307.275862,0.061323,0.000655,64.045172,21.632069,12.15,0.41,1.762414

[전체 칼럼명 목록]
['videoId', 'title', 'publishedAt', 'duration_iso', 'duration_seconds', '장르', '조회수', '좋아요수', '댓글수', '좋아요율', '댓글율', '알파벳비율', '한글비율', '일어비율', '중국어비율', '기타비율', 'Unnamed: 16', 'Unnamed: 17', '평균', '표준편차', 'Unnamed: 20', '장르명', '장르비율', '장르별 평균 조회수', '장르별 평균 좋아요수', '장르별 평균 댓글수', '장르별 평균 좋아요율', '장르별 평균 댓글율', '장르별 평균 알파벳비율', '장르별 평균 한글비율', '장르별 평균 일어비율', '장르별 평균 중국어비율', '장르별 평균 기타비율']

[숫자형 변환 후 데이터 미리보기]

       조회수   좋아요수  댓글수      좋아요율       댓글율  알파벳비율   한글비율   일어비율
0  2954525  93382  388  0.031606  0.000131  50.55  27.47  16.76
1  3492325  80323  407  0.023000  0.000117  53.70  20.11  23.54
2  2638697  64422  247  0.024414  0.000094  59.73  21.68  14.60
3  2645603  63850  358  0.024134  0.000135  55.93  25.84  14.89
4   283185  19425  129  0.068595  0.000456  63.93  25.41   9.02

원본 행 개수: 647
결측치 제거 후 행 개수: 647

[스피어만 상관계수 행렬]

,조회수,좋아요수,댓글수,좋아요율,댓글율,알파벳비율,한글비율,일어비율
조회수,1.000000,0.974646,0.869713,-0.787407,-0.820334,0.241313,-0.215239,-0.131300
좋아요수,0.974646,1.000000,0.898120,-0.643935,-0.744540,0.311174,-0.293938,-0.097508
댓글수,0.869713,0.898120,1.000000,-0.549130,-0.474147,0.239385,-0.176324,-0.166390
좋아요율,-0.787407,-0.643935,-0.549130,1.000000,0.826344,0.033501,-0.072009,0.162028
댓글율,-0.820334,-0.744540,-0.474147,0.826344,1.000000,-0.158197,0.165154,0.074642
알파벳비율,0.241313,0.311174,0.239385,0.033501,-0.158197,1.000000,-0.697088,-0.401322
한글비율,-0.215239,-0.293938,-0.176324,-0.072009,0.165154,-0.697088,1.000000,-0.173926
일어비율,-0.131300,-0.097508,-0.166390,0.162028,0.074642,-0.401322,-0.173926,1.000000

[상관계수]

,조회수,좋아요수,댓글수,좋아요율,댓글율,알파벳비율,한글비율,일어비율
조회수,1.000000,0.974646,0.869713,-0.787407,-0.820334,0.241313,-0.215239,-0.131300
좋아요수,0.974646,1.000000,0.898120,-0.643935,-0.744540,0.311174,-0.293938,-0.097508
댓글수,0.869713,0.898120,1.000000,-0.549130,-0.474147,0.239385,-0.176324,-0.166390
좋아요율,-0.787407,-0.643935,-0.549130,1.000000,0.826344,0.033501,-0.072009,0.162028
댓글율,-0.820334,-0.744540,-0.474147,0.826344,1.000000,-0.158197,0.165154,0.074642
알파벳비율,0.241313,0.311174,0.239385,0.033501,-0.158197,1.000000,-0.697088,-0.401322
한글비율,-0.215239,-0.293938,-0.176324,-0.072009,0.165154,-0.697088,1.000000,-0.173926
일어비율,-0.131300,-0.097508,-0.166390,0.162028,0.074642,-0.401322,-0.173926,1.000000

[p-value]

,조회수,좋아요수,댓글수,좋아요율,댓글율,알파벳비율,한글비율,일어비율
조회수,0.000000e+00,0.000000e+00,5.763834e-200,1.194094e-137,1.113938e-158,5.024623e-10,3.216975e-08,8.145038e-04
좋아요수,0.000000e+00,0.000000e+00,2.582157e-232,4.765216e-77,2.679959e-115,5.416409e-16,2.321984e-14,1.308859e-02
댓글수,5.763834e-200,2.582157e-232,0.000000e+00,3.094953e-52,1.419130e-37,6.952556e-10,6.430241e-06,2.101425e-05
좋아요율,1.194094e-137,4.765216e-77,3.094953e-52,0.000000e+00,5.494103e-163,3.949196e-01,6.718046e-02,3.460974e-05
댓글율,1.113938e-158,2.679959e-115,1.419130e-37,5.494103e-163,0.000000e+00,5.308371e-05,2.423797e-05,5.775079e-02
알파벳비율,5.024623e-10,5.416409e-16,6.952556e-10,3.949196e-01,5.308371e-05,0.000000e+00,2.866088e-95,1.965318e-26
한글비율,3.216975e-08,2.321984e-14,6.430241e-06,6.718046e-02,2.423797e-05,2.866088e-95,0.000000e+00,8.610329e-06
일어비율,8.145038e-04,1.308859e-02,2.101425e-05,3.460974e-05,5.775079e-02,1.965318e-26,8.610329e-06,0.000000e+00

저장 완료:
- correlation_matrix_spearman.csv
- correlation_coef.csv
- correlation_p_value.csv

# 스피어만 상관계수 분석

In [ ]:
# ==============================
# 1. 라이브러리 불러오기
# ==============================
import pandas as pd
import numpy as np
from google.colab import files

# ==============================
# 2. 엑셀 파일 업로드
# ==============================
uploaded = files.upload()

# 업로드한 파일명 가져오기
file_name = list(uploaded.keys())[0]
print(f"업로드된 파일: {file_name}")

# ==============================
# 3. 첫 번째 시트 불러오기
# ==============================
df = pd.read_excel(file_name, sheet_name=0)

print("\n[데이터 미리보기]")
display(df.head())

print("\n[칼럼명 목록]")
print(df.columns.tolist())

# ==============================
# 4. 사용할 칼럼명 지정
# 실제 엑셀 칼럼명에 맞게 수정하세요
# ==============================
columns_for_corr = [
    '조회수',
    '좋아요수',
    '댓글수',
    '알파벳비율',
    '한글비율',
    '일어비율',
    '중국어비율',
    '기타비율'
]

# ==============================
# 5. 선택한 칼럼만 추출
# ==============================
data = df[columns_for_corr].copy()

# 숫자형으로 변환 (문자/쉼표 섞여 있어도 처리)
for col in columns_for_corr:
    data[col] = (
        data[col]
        .astype(str)
        .str.replace(',', '', regex=False)   # 1,234 같은 쉼표 제거
        .str.strip()
    )
    data[col] = pd.to_numeric(data[col], errors='coerce')

print("\n[선택 변수 데이터 미리보기]")
display(data.head())

# ==============================
# 6. 결측치 제거
# 상관분석에 필요한 행만 사용
# ==============================
data_clean = data.dropna()

print(f"\n원본 행 개수: {len(data)}")
print(f"결측치 제거 후 행 개수: {len(data_clean)}")

# ==============================
# 7. 상관분석 실행
# method='spearman' 추천
# 필요하면 'pearson'으로 변경 가능
# ==============================
corr_matrix = data_clean.corr(method='spearman')

print("\n[스피어만 상관계수 행렬]")
display(corr_matrix)

# ==============================
# 8. CSV 파일로 저장하고 다운로드
# ==============================
output_file = 'correlation_matrix_spearman.csv'
corr_matrix.to_csv(output_file, encoding='utf-8-sig')

files.download(output_file)

Saving 르세라핌 분석 시트.xlsx to 르세라핌 분석 시트.xlsx
업로드된 파일: 르세라핌 분석 시트.xlsx

[데이터 미리보기]

,channelTitle,videoId,title,publishedAt,duration_iso,duration_seconds,format,categoryId,categoryTitle,topicCategories,viewCount,likeCount,commentCount,HANGUL_PCT,JAPANESE_PCT,ALPHABET_PCT,CHINESE_PCT,OTHER_PCT,like_PCT,comment_PCT
0,LE SSERAFIM,GsyIPMg2ZIU,dive into the ocean!,2026-03-29T12:01:04Z,PT13S,13,Shorts,10,음악,Lifestyle_(sociology),477768,58996,786,15.44,4.25,79.04,0.14,1.13,0.123483,0.001645
1,LE SSERAFIM,5eM-BHBMB98,시먼딩에서도 Eat it up 😆,2026-03-26T11:00:10Z,PT25S,25,Shorts,10,음악,Food,171662,14415,174,27.45,11.11,56.86,3.27,1.31,0.083973,0.001014
2,LE SSERAFIM,rhTAqE0JH4o,I am KAZUHA,2026-03-23T11:00:22Z,PT53S,53,Shorts,10,음악,Hobby,503341,33538,459,26.48,8.45,63.93,0.46,0.68,0.066631,0.000912
3,LE SSERAFIM,dE2AMWfK2dY,LE SSERAFIM (르세라핌) VR CONCERT : INVITATION Teaser,2026-03-20T09:00:02Z,PT26S,26,Shorts,10,음악,Electronic_music,96979,8990,242,21.96,10.75,64.02,0.47,2.80,0.092700,0.002495
4,LE SSERAFIM,87yyjd5-xMw,우리 했어요! Makeup Swap 했어요! 🪄,2026-03-16T11:00:26Z,PT32S,32,Shorts,10,음악,Lifestyle_(sociology),227070,15999,199,27.57,6.49,64.86,0.54,0.54,0.070458,0.000876

[칼럼명 목록]
['channelTitle', 'videoId', 'title', 'publishedAt', 'duration_iso', 'duration_seconds', 'format', 'categoryId', 'categoryTitle', 'topicCategories', 'viewCount', 'likeCount', 'commentCount', 'HANGUL_PCT', 'JAPANESE_PCT', 'ALPHABET_PCT', 'CHINESE_PCT', 'OTHER_PCT', 'like_PCT', 'comment_PCT']

KeyError: "None of [Index(['조회수', '좋아요수', '댓글수', '알파벳비율', '한글비율', '일어비율', '중국어비율', '기타비율'], dtype='object')] are in the [columns]"

#알파벳 바트 토픽 모델링

In [ ]:
!pip -q install bertopic sentence-transformers umap-learn hdbscan pandas openpyxl tqdm nltk
!pip -q install "transformers<5"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 41.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 20.5 MB/s eta 0:00:00

In [ ]:
import os
import pandas as pd

from google.colab import files
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

# =========================
# 설정
# =========================
MAX_DOCS = None
MIN_TOPIC_SIZE = 150
NR_TOPICS = "auto"
MIN_DOC_WORDS = 4   # 너무 짧은 문서만 제외

# =========================
# 엑셀 저장 + 다운로드 함수
# =========================
def save_excel_with_original_sheets(original_path, extra_sheets: dict, out_path):
    xls = pd.ExcelFile(original_path)

    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        # 원본 시트 유지
        for sh in xls.sheet_names:
            pd.read_excel(original_path, sheet_name=sh).to_excel(
                writer,
                sheet_name=sh[:31],
                index=False
            )

        # 추가 시트 저장
        for sh_name, df_sheet in extra_sheets.items():
            df_sheet.to_excel(writer, sheet_name=sh_name[:31], index=False)

    print("저장 완료:", out_path)
    files.download(out_path)

# =========================
# 1) 원본 파일 업로드
# =========================
uploaded = files.upload()
in_path = next(iter(uploaded.keys()))
print("업로드된 파일:", in_path)

xls = pd.ExcelFile(in_path)
print("시트:", xls.sheet_names)

if "ALPHABET" not in xls.sheet_names:
    raise ValueError(f"'ALPHABET' 시트가 없습니다. 현재 시트: {xls.sheet_names}")

df = pd.read_excel(in_path, sheet_name="ALPHABET")

if "text" not in df.columns:
    raise ValueError(f"ALPHABET 시트에 'text' 컬럼이 없습니다. 현재 컬럼: {list(df.columns)}")

print("ALPHABET rows:", len(df))

# =========================
# 2) 원문 그대로 사용
#    - 결측 제거
#    - 앞뒤 공백 제거
#    - 너무 짧은 문서만 제외
# =========================
df["text_original"] = df["text"].fillna("").astype(str).str.strip()
df["word_count"] = df["text_original"].apply(lambda x: len(x.split()) if x else 0)

before_count = len(df)
df = df[df["word_count"] >= MIN_DOC_WORDS].copy()
after_count = len(df)

docs = df["text_original"].tolist()

if MAX_DOCS is not None and len(docs) > MAX_DOCS:
    df = df.iloc[:MAX_DOCS].copy()
    docs = docs[:MAX_DOCS]

if len(docs) < MIN_TOPIC_SIZE:
    raise ValueError(
        f"문서 수가 너무 적습니다: {len(docs)} (MIN_TOPIC_SIZE={MIN_TOPIC_SIZE})"
    )

print(f"짧은 문서 제거 후 문서 수: {len(docs):,}")

# =========================
# 3) 영어 전용 임베딩 모델
# =========================
embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

# =========================
# 4) 토픽 키워드 표현용 벡터라이저
#    - 임베딩 전 불용어 제거 대신 여기서 처리
# =========================
vectorizer_model = CountVectorizer(
    stop_words="english",
    ngram_range=(1, 2)
)

# =========================
# 5) BERTopic
# =========================
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    language="english",
    min_topic_size=MIN_TOPIC_SIZE,
    nr_topics=NR_TOPICS,
    calculate_probabilities=False,
    low_memory=True,
    verbose=False
)

topics, _ = topic_model.fit_transform(docs)
df["topic_id"] = topics

# =========================
# 6) 토픽 요약 테이블
# =========================
info = topic_model.get_topic_info()
info_valid = info[info["Topic"] != -1].copy()   # outlier 제외

rows = []
for topic_id in info_valid["Topic"].tolist():
    topic_words = topic_model.get_topic(topic_id) or []
    keywords = [word for word, _ in topic_words]

    count = int(info_valid.loc[info_valid["Topic"] == topic_id, "Count"].values[0])

    rows.append({
        "topic_id": topic_id,
        "count": count,
        "keywords_top10": ", ".join(keywords[:10])
    })

df_topic_sum = (
    pd.DataFrame(rows)
    .sort_values("count", ascending=False)
    .reset_index(drop=True)
)

# =========================
# 7) 실행 요약
# =========================
outlier_count = int((df["topic_id"] == -1).sum())

df_cluster_summary = pd.DataFrame([
    {
        "text_column_used": "text_original",
        "original_rows": before_count,
        "rows_after_short_doc_filter": after_count,
        "total_docs_used": len(df),
        "outlier_docs": outlier_count,
        "non_outlier_docs": len(df) - outlier_count,
        "num_topics_excluding_outlier": len(df_topic_sum),
        "MIN_DOC_WORDS": MIN_DOC_WORDS,
        "MIN_TOPIC_SIZE": MIN_TOPIC_SIZE,
        "NR_TOPICS": str(NR_TOPICS),
        "embedding_model": "sentence-transformers/all-MiniLM-L6-v2",
        "language": "english",
        "vectorizer_stop_words": "english",
        "vectorizer_ngram_range": "(1, 2)"
    }
])

print(df_topic_sum.head(10))
print(df_cluster_summary)

# =========================
# 8) 저장 + 다운로드
# =========================
base_name = os.path.splitext(in_path)[0]
out_path = f"{base_name}_alphabet_topics.xlsx"

save_excel_with_original_sheets(
    original_path=in_path,
    extra_sheets={
        "ALPHABET_TOPICS": df,
        "ALPHABET_TOPIC_SUM": df_topic_sum,
        "CLUSTER_SUMMARY": df_cluster_summary
    },
    out_path=out_path
)

/usr/local/lib/python3.12/dist-packages/hdbscan/robust_single_linkage_.py:175: SyntaxWarning: invalid escape sequence '\{'
  $max \{ core_k(a), core_k(b), 1/\alpha d(a,b) \}$.

Saving RUDE_clean (1)_script_split_with_stats.xlsx to RUDE_clean (1)_script_split_with_stats (1).xlsx
업로드된 파일: RUDE_clean (1)_script_split_with_stats (1).xlsx
시트: ['videos', 'comments', 'HANGUL', 'JAPANESE', 'ALPHABET', 'CHINESE', 'OTHER', 'LANG_STATS']
ALPHABET rows: 61015
짧은 문서 제거 후 문서 수: 36,932

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

   topic_id  count                                     keywords_top10
0         0   9809  carmen, di, ini, bisa, banget, nya, lagi, stre...
1         1   2285  song, love, like, really, love song, omg, girl...
2         2   1242  trending, trending indonesia, countries, indon...
3         3   1221  let, lets, 50m, 10m, million, 60m, 20m, 10, li...
4         4    760  hearts2hearts, hearts2hearts hearts2hearts, he...
5         5    738  stella, love stella, english, iconic, speaking...
6         6    727  h2h, win, love h2h, love, song, rude, h2h h2h,...
7         7    603  views, million, million views, let, day, view,...
8         8    590  rude, rude rude, song, acting, nice nice, acti...
9         9    546    34, 35, best, 33, fav, 27, 31, love, 30, iconic
  text_column_used  original_rows  rows_after_short_doc_filter  \
0    text_original          61015                        36932

   total_docs_used  outlier_docs  non_outlier_docs  \
0            36932         15211             21721

   num_topics_excluding_outlier  MIN_DOC_WORDS  MIN_TOPIC_SIZE NR_TOPICS  \
0                            21              4             150      auto

                          embedding_model language vectorizer_stop_words  \
0  sentence-transformers/all-MiniLM-L6-v2  english               english

  vectorizer_ngram_range
0                 (1, 2)
저장 완료: RUDE_clean (1)_script_split_with_stats (1)_alphabet_topics.xlsx

#한글 바트 토픽 모델링

In [ ]:
!pip -q install bertopic sentence-transformers umap-learn hdbscan pandas openpyxl tqdm transformers accelerate
!pip -q install "transformers<5"

In [ ]:
import os
import pandas as pd

from google.colab import files
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

# =========================
# 설정
# =========================
MAX_DOCS = None
MIN_TOPIC_SIZE = 10
NR_TOPICS = "auto"
MIN_DOC_WORDS = 2   # 한국어는 공백 기준 단어 수가 짧게 잡혀서 조금 낮춤

# =========================
# 엑셀 저장 + 다운로드 함수
# =========================
def save_excel_with_original_sheets(original_path, extra_sheets: dict, out_path):
    xls = pd.ExcelFile(original_path)

    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        for sh in xls.sheet_names:
            pd.read_excel(original_path, sheet_name=sh).to_excel(
                writer,
                sheet_name=sh[:31],
                index=False
            )

        for sh_name, df_sheet in extra_sheets.items():
            df_sheet.to_excel(writer, sheet_name=sh_name[:31], index=False)

    print("저장 완료:", out_path)
    files.download(out_path)

# =========================
# 1) 원본 파일 업로드
# =========================
uploaded = files.upload()
in_path = next(iter(uploaded.keys()))
print("업로드된 파일:", in_path)

xls = pd.ExcelFile(in_path)
print("시트:", xls.sheet_names)

if "HANGUL" not in xls.sheet_names:
    raise ValueError(f"'HANGUL' 시트가 없습니다. 현재 시트: {xls.sheet_names}")

df = pd.read_excel(in_path, sheet_name="HANGUL")

if "text" not in df.columns:
    raise ValueError(f"HANGUL 시트에 'text' 컬럼이 없습니다. 현재 컬럼: {list(df.columns)}")

print("HANGUL rows:", len(df))

# =========================
# 2) 원문 그대로 사용
# =========================
df["text_original"] = df["text"].fillna("").astype(str).str.strip()
df["word_count"] = df["text_original"].apply(lambda x: len(x.split()) if x else 0)

before_count = len(df)
df = df[df["word_count"] >= MIN_DOC_WORDS].copy()
after_count = len(df)

docs = df["text_original"].tolist()

if MAX_DOCS is not None and len(docs) > MAX_DOCS:
    df = df.iloc[:MAX_DOCS].copy()
    docs = docs[:MAX_DOCS]

if len(docs) < MIN_TOPIC_SIZE:
    raise ValueError(
        f"문서 수가 너무 적습니다: {len(docs)} (MIN_TOPIC_SIZE={MIN_TOPIC_SIZE})"
    )

print(f"짧은 문서 제거 후 문서 수: {len(docs):,}")

# =========================
# 3) 한국어 전용 임베딩 모델
# =========================
embedding_model = SentenceTransformer(
    "jhgan/ko-sroberta-multitask"
)

# =========================
# 4) 한국어용 벡터라이저
# =========================
vectorizer_model = CountVectorizer(
    ngram_range=(1, 2),
    token_pattern=r"(?u)\b\w+\b"
)

# =========================
# 5) BERTopic
# =========================
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    language="multilingual",
    min_topic_size=MIN_TOPIC_SIZE,
    nr_topics=NR_TOPICS,
    calculate_probabilities=False,
    low_memory=True,
    verbose=False
)

topics, _ = topic_model.fit_transform(docs)
df["topic_id"] = topics

# =========================
# 6) 토픽 요약 테이블
# =========================
info = topic_model.get_topic_info()
info_valid = info[info["Topic"] != -1].copy()

rows = []
for topic_id in info_valid["Topic"].tolist():
    topic_words = topic_model.get_topic(topic_id) or []
    keywords = [word for word, _ in topic_words]

    count = int(info_valid.loc[info_valid["Topic"] == topic_id, "Count"].values[0])

    rows.append({
        "topic_id": topic_id,
        "count": count,
        "keywords_top10": ", ".join(keywords[:10])
    })

df_topic_sum = (
    pd.DataFrame(rows)
    .sort_values("count", ascending=False)
    .reset_index(drop=True)
)

# =========================
# 7) 실행 요약
# =========================
outlier_count = int((df["topic_id"] == -1).sum())

df_cluster_summary = pd.DataFrame([
    {
        "sheet_used": "HANGUL",
        "text_column_used": "text_original",
        "original_rows": before_count,
        "rows_after_short_doc_filter": after_count,
        "total_docs_used": len(df),
        "outlier_docs": outlier_count,
        "non_outlier_docs": len(df) - outlier_count,
        "num_topics_excluding_outlier": len(df_topic_sum),
        "MIN_DOC_WORDS": MIN_DOC_WORDS,
        "MIN_TOPIC_SIZE": MIN_TOPIC_SIZE,
        "NR_TOPICS": str(NR_TOPICS),
        "embedding_model": "jhgan/ko-sroberta-multitask",
        "language": "multilingual",
        "vectorizer_ngram_range": "(1, 2)",
        "vectorizer_token_pattern": r"(?u)\b\w+\b"
    }
])

print(df_topic_sum.head(10))
print(df_cluster_summary)

# =========================
# 8) 저장 + 다운로드
# =========================
base_name = os.path.splitext(in_path)[0]
out_path = f"{base_name}_hangul_topics.xlsx"

save_excel_with_original_sheets(
    original_path=in_path,
    extra_sheets={
        "HANGUL_TOPICS": df,
        "HANGUL_TOPIC_SUM": df_topic_sum,
        "CLUSTER_SUMMARY": df_cluster_summary
    },
    out_path=out_path
)

Saving RUDE_clean (1)_script_split_with_stats (1)_alphabet_topics.xlsx to RUDE_clean (1)_script_split_with_stats (1)_alphabet_topics (1).xlsx
업로드된 파일: RUDE_clean (1)_script_split_with_stats (1)_alphabet_topics (1).xlsx
시트: ['videos', 'comments', 'HANGUL', 'JAPANESE', 'ALPHABET', 'CHINESE', 'OTHER', 'LANG_STATS', 'ALPHABET_TOPICS', 'ALPHABET_TOPIC_SUM', 'CLUSTER_SUMMARY']
HANGUL rows: 4048
짧은 문서 제거 후 문서 수: 3,621

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/744 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/585 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/442M [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

   topic_id  count                                     keywords_top10
0         0    926          너무, 노래, 스텔라, 진짜, 좋다, 정말, 이, 너무 좋다, 하투하, 다
1         1    157  하투하, 사랑해, 하츠투하츠, 화이팅, 대박나자, 하투하 대박나자, 하투하 화이팅,...
2         2     96  di, ada, orang, yang, dengan, saya, dari, sang...
3         3     90  카르멘, 카르멘은, 예뻐요, 정말, 정말 예뻐요, 카르멘은 정말, 아름다워요, 너무...
4         4     82  인도네시아, 한국인, koreans, 합니다, 우리는, 침팬지들이, 침팬지들, 인도...
5         5     68     2, 34, 1, 35, 2 34, 1 34, 2 35, 33, 1 33, 1 35
6         6     65       1위, 축하해, 오늘, 음방, 멜론, 축하, 1주년, 데뷔, 순위, 데뷔 1주년
7         7     65       이안이, 이안, 1 33, 33, 정이안, 1, 이안아, 파트, 뽀뽀, 뽀뽀귀신
8         8     61  루드, 애드롸잇, 메잌미, 메잌미 애드롸잇, 유캔, 미, 이게 나라구, 나라구, 드...
9         9     52  조회수, 1억, 조회수 1억, 1억뷰, 4천만, 회를, 5세대, 좋아요, 5천만, ...
  sheet_used text_column_used  original_rows  rows_after_short_doc_filter  \
0     HANGUL    text_original           4048                         3621

   total_docs_used  outlier_docs  non_outlier_docs  \
0             3621          1011              2610

   num_topics_excluding_outlier  MIN_DOC_WORDS  MIN_TOPIC_SIZE NR_TOPICS  \
0                            47              2              10      auto

               embedding_model      language vectorizer_ngram_range  \
0  jhgan/ko-sroberta-multitask  multilingual                 (1, 2)

  vectorizer_token_pattern
0              (?u)\b\w+\b
저장 완료: RUDE_clean (1)_script_split_with_stats (1)_alphabet_topics (1)_hangul_topics.xlsx